url: https://github.com/dimaty26/dimaty26.github.io
baseurl: 

# Site settings
title: Follow
email: dimaty26rus@mail.ru
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Anton GRIGOREV
  pic: 1
  position: Business analytics and strategy development
  social:
    - title: github
      url: https://github.com/BaldyAsh
    - title: facebook
      url: https://www.facebook.com/profile.php?id=100014712275768
    - title: twitter
      url: https://twitter.com/CryptoBaldyAsh

- name: Georgiy FESENKO
  pic: 2
  position: Head of services and products development
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Rishat GILMANOV
  pic: 3
  position: Main Smart-Trading Modules developer and data scientist
  social:
    - title: twitter
      url: https://twitter.com/GilmanovR
    - title: facebook
      url: https://github.com/Ir1ha
    - title: github
      url: https://github.com/Ir1ha

- name: Gleb ZABLUDOVSKY
  pic: 4
  position: Main backend developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: github
      url: https://github.com/GlebZabl

- name: Anton DMITRIEV
  pic: 5
  position: Main frontend developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: github
      url: https://github.com/kabachok169

- name: Egor KURNIKOV
  pic: 6
  position: Main mobile developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: github
      url: https://github.com/kurnegor

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
